spring:
  application:
    name: DatingApp

  datasource:
    url: jdbc:mysql://localhost:3306/datingapp
    username: root
    password: trungkien

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  storage:
    bucket: gs://datingapp-f4ecb.appspot.com
